# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# xho95's Swift Lift

# Site settings
title: let xho95 = Programmer(with: Swift)
email: xho1995@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Apple에서 공개한 새로운 언어인 Swift를 공부하고 정리하는 사이트였는데, 배가 점점 산으로 가고 있습니다.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://xho95.github.io" # the base hostname & protocol for your site
twitter_username: xho951
github_username:  xho95
facebook_username: xho1995

# The production_url is only used when full-domain names are needed
# such as sitemap.txt
# Most places will/should use BASE_PATH to make the urls
#
# If you have set a CNAME (pages.github.com) set your custom domain here.
# Else if you are pushing to username.github.io, replace with your username.
# Finally if you are pushing to a GitHub project page, include the project name at the end.
production_url : https://xho95.github.io

# Includes an icon in the footer for each username you enter
# footer-links:
#   dribbble:
#   email: xho1995@gmail.com
#   facebook: xho1995
#   flickr:
#   github: xho95
#   instagram:
#   linkedin:
#   pinterest:
#   rss: # just type anything here for a working RSS icon
#   twitter: xho95
#   stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
#   youtube: # channel/<your_long_string> or user/<user-name>
#   googleplus: xho95 # anything in your profile username that comes after plus.google.com/

# Build settings
# redcarpet:
#  extensions: ["tables", "autolink", "strikethrough", "space_after_header", "fenced_code_blocks", "footnotes"]

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: xho95githubio
